# =============================================================================
# Colores base (custom palette)
# =============================================================================

$bg0   = rgba(1f1a24ff)   # fondo principal
$bg1   = rgba(2a2232ff)   # fondo secundario
$bg2   = rgba(4a3a57ff)   # inactivos / bordes suaves

$fg0   = rgba(e6e1ebff)   # texto principal
$fg1   = rgba(a0a0a2ff)   # texto secundario

$purple0 = rgba(6f4683ff)
$purple1 = rgba(886593ff)
$purple2 = rgba(b58ac6ff)

$red0    = rgba(e23e64ff)
$orange0 = rgba(e69d25ff)
$yellow0 = rgba(f2d16bff)

$cyan0   = rgba(4fb3a5ff)
$blue0   = rgba(5fafd7ff)

# =============================================================================
# Configuracion de colores de hyprland
# =============================================================================

general {
    col.active_border   = $red0 $orange0 70deg
    col.inactive_border = $bg2

    border_size = 4

    gaps_in = 10
    gaps_out = 20
}

decoration {
    rounding = 20
    dim_special = 0.1
    dim_inactive = true
    dim_strength = 0.20

    blur {
        enabled = true
        size = 5
        passes = 3
        new_optimizations = true
        ignore_opacity = true
    }
}

misc {
    col.splash = $purple0
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    font_family = CaskaydiaCove Nerd Font
    enable_swallow = true
    on_focus_under_fullscreen = 1
}

windowrule = match:fullscreen true,border_color $purple1 $cyan0 70deg
